enum SchemaTypesReference {
  Employee = "employee",
  Candidate = "candidate",
  EmployeePaper = "employee-paper",
  Complaint = "complaint",
  Attendance = "attendance",
  Group = "group",
  TEMPLATE = "template",
  HIRING = "hiring",
  EVENT = "event",
  CANDIDATE_QUESTION = "candidate-question",
  Linkedin_Accounts = "linkedin_accounts",
  Conversation = "conversation",
  Message = "message",
  Room = "room",
  Supplies = "supplies",
  Ticket = "ticket",
  Receipt = "receipt",
  Seen = "seen",
  SocialMedia = "socialMedia",
  SocialMediaAccount = "socialAccount",
  SocialMediaComment = "socialMediaComment",
  TwitterData = "twitterData",
  RedditAccount = "RedditAccount",
  Payroll = "payroll",
  Subscription = "subscription",
  BankAccount = "bankAccount",
  Assets = "assets",
  RealState = "realState",
  Equipment = "equipment",
  DigitalAsset = "digital-asset",
  BrandEmail = "brand-email",
  UserEmailsSubscription = "user-emails-subscription",
  NewsLetters = "news-letter",
  Analytics = "analytics",
  Prompt = "prompt",
  Audiences = "audiences",
  Telegram = "telegram",
  SocialMediaGroups="socialmediagroups",
  SocialMediaPosts="socialmediaposts",
  TelegramMessage = "telegram_message",
}

export { SchemaTypesReference };
